---
abstract: 'Services for Bot::Backbone that do things on the web'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bot-Backbone-Service-Web
requires:
  Bot::Backbone: 0
  Bot::Backbone::Service: 0
  Bot::Backbone::Service::Role::Responder: 0
  Bot::Backbone::Service::Role::Service: 0
  URI::Find: 0
  URI::Title: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Bot-Backbone-Service-Web
  repository: git://github.com/zostay/Bot-Backbone-Service-Web.git
version: 0.142250
